"""
config.py — CONFIGURARE COMPLETA Forex Radar v4
"""
import os
from dotenv import load_dotenv
load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID   = os.getenv("TELEGRAM_CHAT_ID", "")

SYMBOLS_3MIN = [
    "EURUSD","GBPUSD","USDJPY","USDCHF",
    "AUDUSD","USDCAD","EURJPY","GBPJPY",
]
SYMBOLS_10MIN = [
    "NZDUSD","EURGBP","EURAUD","GBPAUD",
    "EURCAD","GBPCAD","GBPCHF","GBPNZD",
    "AUDJPY","CADJPY",
]
SYMBOLS = SYMBOLS_3MIN + SYMBOLS_10MIN

EXPIRY_OPTIONS_3MIN  = [3, 5, 10]
EXPIRY_OPTIONS_10MIN = [10, 15]
EXPIRY_OPTIONS       = EXPIRY_OPTIONS_3MIN

SCAN_INTERVAL    = 60
CANDLES_REQUIRED = 120

DATA_SOURCE           = "dukascopy"
MIN_CANDLES_REQUIRED  = 100
MAX_FETCH_LATENCY_SEC = 2.0

ATR_PERIOD        = 14
FRACTAL_N         = 2
FRACTAL_PROXIMITY = 0.5
MAX_SR_LEVELS     = 8

FPT_QUANTILE        = 0.95
MIN_FPT_PROB        = 0.65
MIN_SR_DISTANCE_ATR = 0.50

OU_WINDOW_MIN       = 60
Z_SCORE_THRESHOLD   = 1.5
MIN_WIN_PROBABILITY = 0.55

W1 = 0.55
W2 = 0.25
W3 = 0.20
MIN_FINAL_SCORE   = 0.20
ATR_HIGH_VOL_MULT = 1.5
ATR_LOW_VOL_MULT  = 0.5

HURST_WINDOW              = 60
REQUIRE_REGIME_ALIGNMENT  = True
HURST_MOMENTUM_THRESHOLD  = 0.58
HURST_MR_THRESHOLD        = 0.42

GLOBAL_COOLDOWN_SEC   = 300
SYMBOL_COOLDOWN_SEC   = 600
MAX_SIGNALS_PER_CYCLE = 1

RANK_W_PROB       = 0.25
RANK_W_DIST       = 0.25
RANK_W_HURST      = 0.10
RANK_W_SCORE      = 0.20
RANK_W_CONFLUENCE = 0.20

ATR_RATIO_MIN = 0.30
ATR_RATIO_MAX = 2.50

MIN_STABILITY_SCORE  = 0.70
STABILITY_EMA_PERIOD = 20
STABILITY_LOOKBACK   = 20

MAX_SPREAD_ATR_RATIO = 0.50

SESSION_FILTER_ENABLED    = True
SESSION_ALLOWED_START_UTC = 5
SESSION_ALLOWED_END_UTC   = 23

RSI_PERIOD                  = 14
RSI_OVERBOUGHT              = 70
RSI_OVERSOLD                = 30
CONFLUENCE_RSI_WEIGHT       = 0.5
CONFLUENCE_STABILITY_WEIGHT = 0.5

MTF_FILTER_ENABLED = True
MTF_EMA_FAST       = 9
MTF_EMA_SLOW       = 21

NEWS_FILTER_ENABLED    = True
NEWS_BUFFER_BEFORE_MIN = 10
NEWS_BUFFER_AFTER_MIN  = 5

PF_TRACKING_ENABLED     = True
PF_MIN_SIGNALS_FOR_EVAL = 10
PF_SUSPEND_THRESHOLD    = 1.05
PF_RESUME_THRESHOLD     = 1.20
PF_LOOKBACK_SIGNALS     = 50

# ── Lead Time ────────────────────────────────────────────────────────────────
# Semnalul este trimis cu LEAD_TIME_SEC secunde INAINTE de intrare.
# La 90 sec: "Intrare la 20:15:30 UTC" — ai timp sa deschizi pozitia.
LEAD_TIME_SEC = 90
